---- Base app schema

-- User
CREATE TABLE "user" ( id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY, username varchar(128) NOT NULL UNIQUE);

-- Finance
CREATE TYPE entry_type AS ENUM ('invoice', 'payment');
CREATE TABLE "finance" ( id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY, to_from varchar(256) NOT NULL, details varchar(256) NOT NULL, amount REAL NOT NULL, type entry_type NOT NULL);

